### ISSUE TITLE
Cross origin null forbidden

### ISSUE THREAD

**Issue by thecodegoddess** [remedyhealth/contentfaux#16]
This could just be our setup but figured I would mention here just incase. It appears that the response is looking for a couple of headers to be set on the response for the mock calls to work.
I get this error to start `Error: Cross origin null forbidden` so I added the following:
 
```javascript
...
res.setHeader('Access-Control-Allow-Origin', '*');
```
Then I got this error `Error: Headers X-Contentful-User-Agent,Authorization,user-agent forbidden` so I added the second line.
 
```javascript
...
res.setHeader('Access-Control-Allow-Origin', '*');
res.setHeader('Access-Control-Allow-Headers', 'X-Contentful-User-Agent,Authorization,user-agent');
```

**Comment by mrsteele** [comment]
Hey @thecodegoddess and thank you for bringing this to our attention!

Might I request you submit a PR with this fix? It sounds like you were able to get it all working relatively easily and would love for others to benefit from this as well.

**Comment by thecodegoddess** [comment]
@mrsteele Sure, I can put that together!
